const dummyData = {
  title: {
    text: "믿고 장보는 공식 브랜드",
    shortcutText: "전체보기",
    shortcutLandingUrl: "https://www.gmarket.co.kr/n/emartmall/brand",
  },
  sdBrandItemCatalogs: [
    {
      sdBrandName: "노브랜드",
      sdBrandPageUrl:
        "https://www.gmarket.co.kr/n/emartmall/brand?brandCode=31170",
      brandLogoImage: {
        offImageUrl:
          "//image.gmarket.co.kr/hanbando/202207/a768ab02-64c7-423d-a468-5d7b2ef00ec8.png",
        onImageUrl:
          "//image.gmarket.co.kr/hanbando/202207/5571514d-c1ec-4451-b8e4-b8c2d3e5cebf.png",
      },
      items: [
        {
          buyCount: 59127,
          buyUnitCount: 1,
          discountRate: 0,
          hasOption: false,
          imageUrl: "//gdimg.gmarket.co.kr/2519000890/still/400?ver=1749772824",
          isAdult: false,
          isBigSmileItem: false,
          isCartVisible: true,
          isSoldOut: false,
          itemName: "노브랜드냉동 삼겹살 바로구이 (1000g)",
          itemNo: "2519000890",
          itemPrice: 9980,
          itemUrl: "https://item.gmarket.co.kr/Item?goodscode=2519000890",
          rank: 1,
          minBuyCount: 0,
          reviewPoint: {
            starPoint: 4.76,
            reviewCount: 6655,
          },
          sellerInfo: {
            sellCustNo: "155104283",
            isLmoOfficialSeller: false,
            isFashionSquareSeller: false,
            isBrandOfficialSeller: false,
          },
          sellPrice: 9980,
          tagLabels: [
            {
              code: 0,
              text: "전단상품",
            },
          ],
          dealImageUrl: "",
          deliveryCode: "M",
          lcode: "100000020",
          mcode: "200001217",
          scode: "300028967",
        },
        {
          buyCount: 231559,
          buyUnitCount: 1,
          discountRate: 0,
          hasOption: false,
          imageUrl: "//gdimg.gmarket.co.kr/2522715372/still/400?ver=1746054618",
          isAdult: false,
          isBigSmileItem: false,
          isCartVisible: true,
          isSoldOut: false,
          itemName: "국산콩두부300g2입",
          itemNo: "2522715372",
          itemPrice: 3480,
          itemUrl: "https://item.gmarket.co.kr/Item?goodscode=2522715372",
          rank: 2,
          minBuyCount: 0,
          reviewPoint: {
            starPoint: 4.77,
            reviewCount: 49280,
          },
          sellerInfo: {
            sellCustNo: "155104283",
            isLmoOfficialSeller: false,
            isFashionSquareSeller: false,
            isBrandOfficialSeller: false,
          },
          sellPrice: 3480,
          tagLabels: "[]",
          dealImageUrl: "",
          deliveryCode: "M",
          lcode: "100000020",
          mcode: "200001222",
          scode: "300020127",
        },
        {
          buyCount: 37413,
          buyUnitCount: 1,
          discountRate: 0,
          hasOption: false,
          imageUrl: "//gdimg.gmarket.co.kr/2519122999/still/400?ver=1748385490",
          isAdult: false,
          isBigSmileItem: false,
          isCartVisible: true,
          isSoldOut: false,
          itemName: "노브랜드 3겹 화장지 33m X 30롤",
          itemNo: "2519122999",
          itemPrice: 10580,
          itemUrl: "https://item.gmarket.co.kr/Item?goodscode=2519122999",
          rank: 3,
          minBuyCount: 0,
          reviewPoint: {
            starPoint: 4.75,
            reviewCount: 7847,
          },
          sellerInfo: {
            sellCustNo: "155104283",
            isLmoOfficialSeller: false,
            isFashionSquareSeller: false,
            isBrandOfficialSeller: false,
          },
          sellPrice: 10580,
          tagLabels: "[]",
          dealImageUrl: "",
          deliveryCode: "M",
          lcode: "100000074",
          mcode: "200002936",
          scode: "300028946",
        },
      ],
    },
    {
      sdBrandName: "피코크",
      sdBrandPageUrl:
        "https://www.gmarket.co.kr/n/emartmall/brand?brandCode=26015",
      brandLogoImage: {
        offImageUrl:
          "//image.gmarket.co.kr/hanbando/202207/358bca3b-4811-4672-aa6d-21f6b1008f46.png",
        onImageUrl:
          "//image.gmarket.co.kr/hanbando/202207/f6276d3b-e31a-4f35-be44-6850d97aa991.png",
      },
      items: [
        {
          buyCount: 10171,
          buyUnitCount: 1,
          couponDiscount: {
            discountType: "R",
            discountPrice: "0",
            discountRate: "15",
          },
          discountRate: 0,
          hasOption: false,
          imageUrl: "//gdimg.gmarket.co.kr/2518774407/still/400?ver=1747115838",
          isAdult: false,
          isBigSmileItem: false,
          isCartVisible: true,
          isSoldOut: false,
          itemName: "조선호텔특제육수 포기김치 4kg",
          itemNo: "2518774407",
          itemPrice: 39800,
          itemUrl: "https://item.gmarket.co.kr/Item?goodscode=2518774407",
          rank: 1,
          minBuyCount: 0,
          reviewPoint: {
            starPoint: 4.64,
            reviewCount: 976,
          },
          sellerInfo: {
            sellCustNo: "155104283",
            isLmoOfficialSeller: false,
            isFashionSquareSeller: false,
            isBrandOfficialSeller: false,
          },
          sellPrice: 39800,
          tagLabels: [
            {
              code: 0,
              text: "미식관",
            },
          ],
          dealImageUrl: "",
          deliveryCode: "M",
          lcode: "100000020",
          mcode: "200000221",
          scode: "300001910",
        },
        {
          buyCount: 19144,
          buyUnitCount: 1,
          couponDiscount: {
            discountType: "R",
            discountPrice: "0",
            discountRate: "15",
          },
          discountRate: 9,
          hasOption: false,
          imageUrl: "//gdimg.gmarket.co.kr/2523375631/still/400?ver=1741853471",
          isAdult: false,
          isBigSmileItem: false,
          isCartVisible: true,
          isSoldOut: false,
          itemName: "피코크 쟌슨빌 소시지 부대 찌개 1000g",
          itemNo: "2523375631",
          itemPrice: 10790,
          itemUrl: "https://item.gmarket.co.kr/Item?goodscode=2523375631",
          rank: 2,
          minBuyCount: 0,
          reviewPoint: {
            starPoint: 4.76,
            reviewCount: 4351,
          },
          sellerInfo: {
            sellCustNo: "155104283",
            isLmoOfficialSeller: false,
            isFashionSquareSeller: false,
            isBrandOfficialSeller: false,
          },
          sellPrice: 11980,
          tagLabels: [
            {
              code: 0,
              text: "미식관",
            },
          ],
          dealImageUrl: "",
          deliveryCode: "M",
          lcode: "100000036",
          mcode: "200000642",
          scode: "300028694",
        },
        {
          buyCount: 94885,
          buyUnitCount: 1,
          couponDiscount: {
            discountType: "R",
            discountPrice: "0",
            discountRate: "15",
          },
          discountRate: 0,
          hasOption: false,
          imageUrl: "//gdimg.gmarket.co.kr/2518646310/still/400?ver=1746777987",
          isAdult: false,
          isBigSmileItem: false,
          isCartVisible: true,
          isSoldOut: false,
          itemName: "피코크 에이 클래스 우유 2.3L (1A등급)",
          itemNo: "2518646310",
          itemPrice: 5980,
          itemUrl: "https://item.gmarket.co.kr/Item?goodscode=2518646310",
          rank: 3,
          minBuyCount: 0,
          reviewPoint: {
            starPoint: 4.74,
            reviewCount: 11762,
          },
          sellerInfo: {
            sellCustNo: "155104283",
            isLmoOfficialSeller: false,
            isFashionSquareSeller: false,
            isBrandOfficialSeller: false,
          },
          sellPrice: 5980,
          tagLabels: [],
          dealImageUrl: "",
          deliveryCode: "M",
          lcode: "100000094",
          mcode: "200002376",
          scode: "300021921",
        },
      ],
    },
    {
      sdBrandName: "데이즈",
      sdBrandPageUrl:
        "https://www.gmarket.co.kr/n/emartmall/brand?brandCode=94436",
      brandLogoImage: {
        offImageUrl:
          "//image.gmarket.co.kr/hanbando/202207/9ec95a8c-96c6-42d2-ad38-333124e968aa.png",
        onImageUrl:
          "//image.gmarket.co.kr/hanbando/202207/b65d743d-704f-457c-a78f-87fdfa9e53ff.png",
      },
      items: [
        {
          buyCount: 14,
          buyUnitCount: 1,
          couponDiscount: {
            discountType: "R",
            discountPrice: "0",
            discountRate: "15",
          },
          discountRate: 0,
          hasOption: true,
          imageUrl: "//gdimg.gmarket.co.kr/3211538998/still/400?ver=1741876873",
          isAdult: false,
          isBigSmileItem: false,
          isCartVisible: true,
          isSoldOut: false,
          itemName: "데이즈 팬티스타킹10족",
          itemNo: "3211538998",
          itemPrice: 15800,
          itemUrl: "https://item.gmarket.co.kr/Item?goodscode=3211538998",
          rank: 1,
          minBuyCount: 0,
          reviewPoint: {
            starPoint: 4.67,
            reviewCount: 10,
          },
          sellerInfo: {
            sellCustNo: "155104283",
            isLmoOfficialSeller: false,
            isFashionSquareSeller: false,
            isBrandOfficialSeller: false,
          },
          sellPrice: 15800,
          tagLabels: [],
          dealImageUrl: "",
          deliveryCode: "M",
          lcode: "100000064",
          mcode: "200002587",
          scode: "300003461",
        },
        {
          buyCount: 21,
          buyUnitCount: 1,
          couponDiscount: {
            discountType: "R",
            discountPrice: "0",
            discountRate: "15",
          },
          discountRate: 0,
          hasOption: true,
          imageUrl: "//gdimg.gmarket.co.kr/4323718757/still/400?ver=1741911268",
          isAdult: false,
          isBigSmileItem: false,
          isCartVisible: true,
          isSoldOut: false,
          itemName: "DZ에센셜무지립중목B",
          itemNo: "4323718757",
          itemPrice: 1980,
          itemUrl: "https://item.gmarket.co.kr/Item?goodscode=4323718757",
          rank: 2,
          minBuyCount: 0,
          reviewPoint: {
            starPoint: 5,
            reviewCount: 1,
          },
          sellerInfo: {
            sellCustNo: "155104283",
            isLmoOfficialSeller: false,
            isFashionSquareSeller: false,
            isBrandOfficialSeller: false,
          },
          sellPrice: 1980,
          tagLabels: [],
          dealImageUrl: "",
          deliveryCode: "M",
          lcode: "100000064",
          mcode: "200001419",
          scode: "300023467",
        },
        {
          buyCount: 1,
          buyUnitCount: 1,
          couponDiscount: {
            discountType: "R",
            discountPrice: "0",
            discountRate: "15",
          },
          discountRate: 0,
          hasOption: true,
          imageUrl: "//gdimg.gmarket.co.kr/3504440674/still/400?ver=1747637305",
          isAdult: false,
          isBigSmileItem: false,
          isCartVisible: true,
          isSoldOut: false,
          itemName: "DZ번들여 무압박 2족 K",
          itemNo: "3504440674",
          itemPrice: 6980,
          itemUrl: "https://item.gmarket.co.kr/Item?goodscode=3504440674",
          rank: 3,
          minBuyCount: 0,
          reviewPoint: {
            starPoint: 5,
            reviewCount: 2,
          },
          sellerInfo: {
            sellCustNo: "155104283",
            isLmoOfficialSeller: false,
            isFashionSquareSeller: false,
            isBrandOfficialSeller: false,
          },
          sellPrice: 6980,
          tagLabels: [],
          dealImageUrl: "",
          deliveryCode: "M",
          lcode: "100000064",
          mcode: "200002587",
          scode: "300022514",
        },
        {
          buyCount: 0,
          buyUnitCount: 1,
          couponDiscount: {
            discountType: "R",
            discountPrice: "0",
            discountRate: "15",
          },
          discountRate: 0,
          hasOption: true,
          imageUrl: "//gdimg.gmarket.co.kr/3935284083/still/400?ver=1741909602",
          isAdult: false,
          isBigSmileItem: false,
          isCartVisible: true,
          isSoldOut: false,
          itemName: "행)DZ남성스니커즈5족",
          itemNo: "3935284083",
          itemPrice: 9980,
          itemUrl: "https://item.gmarket.co.kr/Item?goodscode=3935284083",
          rank: 4,
          minBuyCount: 0,
          reviewPoint: {
            starPoint: 0,
            reviewCount: 0,
          },
          sellerInfo: {
            sellCustNo: "155104283",
            isLmoOfficialSeller: false,
            isFashionSquareSeller: false,
            isBrandOfficialSeller: false,
          },
          sellPrice: 9980,
          tagLabels: [],
          dealImageUrl: "",
          deliveryCode: "M",
          lcode: "100000064",
          mcode: "200001419",
          scode: "300023467",
        },
      ],
    },
    {
      sdBrandName: "일렉트로마트",
      sdBrandPageUrl:
        "https://www.gmarket.co.kr/n/emartmall/brand?brandCode=94437",
      brandLogoImage: {
        offImageUrl:
          "//image.gmarket.co.kr/hanbando/202207/9854cd66-ddb3-462f-bb1d-e914ee4b5430.png",
        onImageUrl:
          "//image.gmarket.co.kr/hanbando/202207/35eca044-195d-4cef-a6bd-a2c82d3c9a74.png",
      },
      items: [
        {
          buyCount: 14,
          buyUnitCount: 1,
          couponDiscount: {
            discountType: "R",
            discountPrice: "0",
            discountRate: "15",
          },
          discountRate: 0,
          hasOption: false,
          imageUrl: "//gdimg.gmarket.co.kr/2579820190/still/400?ver=1741862457",
          isAdult: false,
          isBigSmileItem: false,
          isCartVisible: true,
          isSoldOut: false,
          itemName: "일렉트로맨 USB A to C 충전케이블 2M",
          itemNo: "2579820190",
          itemPrice: 4900,
          itemUrl: "https://item.gmarket.co.kr/Item?goodscode=2579820190",
          rank: 1,
          minBuyCount: 0,
          reviewPoint: {
            starPoint: 5,
            reviewCount: 2,
          },
          sellerInfo: {
            sellCustNo: "155104283",
            isLmoOfficialSeller: false,
            isFashionSquareSeller: false,
            isBrandOfficialSeller: false,
          },
          sellPrice: 4900,
          tagLabels: [],
          dealImageUrl: "",
          deliveryCode: "M",
          lcode: "100000056",
          mcode: "200002250",
          scode: "300028635",
        },
        {
          buyCount: 13,
          buyUnitCount: 1,
          couponDiscount: {
            discountType: "R",
            discountPrice: "0",
            discountRate: "15",
          },
          discountRate: 0,
          hasOption: false,
          imageUrl: "//gdimg.gmarket.co.kr/2579820368/still/400?ver=1741862458",
          isAdult: false,
          isBigSmileItem: false,
          isCartVisible: true,
          isSoldOut: false,
          itemName: "일렉트로맨  A to C 충전케이블 1M",
          itemNo: "2579820368",
          itemPrice: 2900,
          itemUrl: "https://item.gmarket.co.kr/Item?goodscode=2579820368",
          rank: 2,
          minBuyCount: 0,
          reviewPoint: {
            starPoint: 4.25,
            reviewCount: 3,
          },
          sellerInfo: {
            sellCustNo: "155104283",
            isLmoOfficialSeller: false,
            isFashionSquareSeller: false,
            isBrandOfficialSeller: false,
          },
          sellPrice: 2900,
          tagLabels: [],
          dealImageUrl: "",
          deliveryCode: "M",
          lcode: "100000056",
          mcode: "200002040",
          scode: "300017010",
        },
        {
          buyCount: 0,
          buyUnitCount: 1,
          couponDiscount: {
            discountType: "R",
            discountPrice: "0",
            discountRate: "15",
          },
          discountRate: 0,
          hasOption: false,
          imageUrl: "//gdimg.gmarket.co.kr/3150208688/still/400?ver=1741880472",
          isAdult: false,
          isBigSmileItem: false,
          isCartVisible: true,
          isSoldOut: false,
          itemName: "일렉트로맨 100W CtoC 소프트 케이블2M",
          itemNo: "3150208688",
          itemPrice: 14900,
          itemUrl: "https://item.gmarket.co.kr/Item?goodscode=3150208688",
          rank: 3,
          minBuyCount: 0,
          reviewPoint: {
            starPoint: 0,
            reviewCount: 0,
          },
          sellerInfo: {
            sellCustNo: "155104283",
            isLmoOfficialSeller: false,
            isFashionSquareSeller: false,
            isBrandOfficialSeller: false,
          },
          sellPrice: 14900,
          tagLabels: [],
          dealImageUrl: "",
          deliveryCode: "M",
          lcode: "100000056",
          mcode: "200002250",
          scode: "300028635",
        },
      ],
    },
    {
      sdBrandName: "몰리스",
      sdBrandPageUrl:
        "https://www.gmarket.co.kr/n/emartmall/brand?brandCode=83129",
      brandLogoImage: {
        offImageUrl:
          "//image.gmarket.co.kr/hanbando/202207/8cf09cbb-bafa-46a7-b176-d19c41a8cb5c.png",
        onImageUrl:
          "//image.gmarket.co.kr/hanbando/202207/759e1a89-3291-4070-a1d6-0cb4eb5dd8c3.png",
      },
      items: [
        {
          buyCount: 1880,
          buyUnitCount: 1,
          couponDiscount: {
            discountType: "R",
            discountPrice: "0",
            discountRate: "15",
          },
          discountRate: 0,
          hasOption: false,
          imageUrl: "//gdimg.gmarket.co.kr/2522883874/still/400?ver=1748848107",
          isAdult: false,
          isBigSmileItem: false,
          isCartVisible: true,
          isSoldOut: false,
          itemName: "몰리스픽 반려견 패드 M 100매",
          itemNo: "2522883874",
          itemPrice: 8500,
          itemUrl: "https://item.gmarket.co.kr/Item?goodscode=2522883874",
          rank: 1,
          minBuyCount: 0,
          reviewPoint: {
            starPoint: 4.73,
            reviewCount: 366,
          },
          sellerInfo: {
            sellCustNo: "155104283",
            isLmoOfficialSeller: false,
            isFashionSquareSeller: false,
            isBrandOfficialSeller: false,
          },
          sellPrice: 8500,
          tagLabels: [],
          dealImageUrl: "",
          deliveryCode: "M",
          lcode: "100000038",
          mcode: "200000306",
          scode: "300002644",
        },
        {
          buyCount: 2620,
          buyUnitCount: 1,
          couponDiscount: {
            discountType: "R",
            discountPrice: "0",
            discountRate: "15",
          },
          discountRate: 0,
          hasOption: false,
          imageUrl: "//gdimg.gmarket.co.kr/2522850457/still/400?ver=1748816554",
          isAdult: false,
          isBigSmileItem: false,
          isCartVisible: true,
          isSoldOut: false,
          itemName: "몰리스픽 반려견 패드 L 45매",
          itemNo: "2522850457",
          itemPrice: 8500,
          itemUrl: "https://item.gmarket.co.kr/Item?goodscode=2522850457",
          rank: 2,
          minBuyCount: 0,
          reviewPoint: {
            starPoint: 4.79,
            reviewCount: 348,
          },
          sellerInfo: {
            sellCustNo: "155104283",
            isLmoOfficialSeller: false,
            isFashionSquareSeller: false,
            isBrandOfficialSeller: false,
          },
          sellPrice: 8500,
          tagLabels: [],
          dealImageUrl: "",
          deliveryCode: "M",
          lcode: "100000038",
          mcode: "200000306",
          scode: "300002644",
        },
        {
          buyCount: 670,
          buyUnitCount: 1,
          couponDiscount: {
            discountType: "R",
            discountPrice: "0",
            discountRate: "15",
          },
          discountRate: 0,
          hasOption: false,
          imageUrl: "//gdimg.gmarket.co.kr/2519496563/still/400?ver=1748816468",
          isAdult: false,
          isBigSmileItem: false,
          isCartVisible: true,
          isSoldOut: false,
          itemName: "몰리스 쉬야응가 1회용 패드 M 100매",
          itemNo: "2519496563",
          itemPrice: 13900,
          itemUrl: "https://item.gmarket.co.kr/Item?goodscode=2519496563",
          rank: 3,
          minBuyCount: 0,
          reviewPoint: {
            starPoint: 4.92,
            reviewCount: 57,
          },
          sellerInfo: {
            sellCustNo: "155104283",
            isLmoOfficialSeller: false,
            isFashionSquareSeller: false,
            isBrandOfficialSeller: false,
          },
          sellPrice: 13900,
          tagLabels: [],
          dealImageUrl: "",
          deliveryCode: "M",
          lcode: "100000038",
          mcode: "200000306",
          scode: "300002644",
        },
      ],
    },
  ],
};
export default dummyData;
